### ISSUE TITLE
<C-space> not toggling box on line

### ISSUE THREAD

**Issue by thecarlhall** [dewyze/vim-tada#2]
I've tried using `<C-space>` to toggle a checkbox but it doesn't do anything for me. Checking `:map` shows `n  <C-Space>   *@:TadaBox<CR>` as the only mapping for ctrl-space. When I run `:TadaBox` it works fine. When I add, `nmap <silent> <leader>r :TadaBox<CR>` to .vimrc, this works fine. Any suggestions of what else I should test? Love the plugin!

**Comment by dewyze** [comment]
Hey @thecarlhall glad to hear you like it!

That's no good if it's not working. Can you give me a minimally failing snippet I can debug with?

**Comment by bjoe2k4** [comment]
<C-Space> has a lot of gotchas on Windows terminal. Seems rather complex to me as also openssh may be involved.

Some context: https://github.com/microsoft/terminal/issues/2865

I've also remapped <C-Space> to something else and it works fine.

**Comment by thecarlhall** [comment]
For context, I'm on Mac using Alacritty w/ tmux and tested with Terminal w/o tmux.

Minimal failing snippet:
```
- Inbox:
  - A test task
```

There's a lot of folks on the internet calling out this keybinding in many places. One fix I've just found from vimwiki was to add this to .vimrc:
`nmap <silent> <C-@> :TadaBox<CR>`

**Comment by dewyze** [comment]
Hmm, @thecarlhall I use Alacritty on Mac w/tmux coincidentally too, I tried <C-space> on every single character in that string and it worked fine.

Any suggestions on what to try?

**Comment by thecarlhall** [comment]
Ha! I haven't yet found anything else trapping this key sequence. Adding the nmap above fixed this on 2 machines (macOS 11 & 12). `<C-V> <C-space>` shows `^@`, so I think the sequence is making through to vim.

I cleaned out my .vimrc to the below text for testing, but still couldn't get `C-space` to call TadaBox until adding the `nmap` line from above. The mystery continues...
```vimrc
set nocompatible
filetype plugin indent on

call plug#begin('~/.vim/bundle')
Plug 'dewyze/vim-tada'
call plug#end()
```

**Comment by thecarlhall** [comment]
Extra data point: I see the issue in Alacritty, Terminal, and now Kitty. I'm starting to wonder if this is deeper than the terminal emulator, or in a custom setting I can't/haven't found.

**Comment by dewyze** [comment]
Alright, so the issue is I am using Neovim, but you are talking about vim. I found that vim doesn't have the `<C-Space>` but it is the same as `<C-@>. [Link](https://vi.stackexchange.com/questions/3072/how-can-i-bind-ctrl-space-to-be-esc-when-not-in-insert-mode-and-to-switch-to-in). Try setting:

```vim
let g:tada_map_box = '<C-@>`
```

**Comment by dewyze** [comment]
If that works for you, I'll see if I can add to the config to detect vim or neovim and set it accordingly.

**Comment by thecarlhall** [comment]
Nailed it! You're also correct in that I'm using Vim (8.2) rather than NeoVim. Thanks for helping me nail this down.

**Comment by dewyze** [comment]
@thecarlhall I think this should fix it, let me know: https://github.com/dewyze/vim-tada/commit/bcf07ace4d6e05a621fa1c97a381ad4a0ab09f9a

**Comment by thecarlhall** [comment]
Works great! I removed `let g:tada_map_box = '<C-@>'` from `.vimrc`, and fetched & rebased your main branch. All is well now 😄
